### ISSUE TITLE
Torchat URI

### ISSUE THREAD

**Issue by HostFat** [jtorchat/jtorchat-old#10]
Some examples:

torchat://|user|f4987bhw394vu9|/
torchat://|group|83ry4v340f80h34wh|pass=87fy5437hdq|/

**Comment by jtorchat** [comment]
Can you explain more what you mean?

**Comment by HostFat** [comment]
This is a feature request.

I'd like to see Jtorchat support some kind of URI scheme.
( they are just some examples/suggestions )

Others:
https://en.wikipedia.org/wiki/Ed2k_URI_scheme
https://en.wikipedia.org/wiki/Magnet_URI_scheme
https://en.bitcoin.it/wiki/URI_Scheme

People will be able to add them on website/everywhere, and users will be able to use them with only a click.
( I repeat, these are just examples ... )

If the user click this link, Jtorchat will catch it and will add/send a request for the user with this id "f4987bhw394vu9"
torchat://|user|f4987bhw394vu9|/

If the user click this link, Jtorchat will open the group chat with this ID "83ry4v340f80h34wh" and it will use this password to access to it "87fy5437hdq"
torchat://|group|83ry4v340f80h34wh|pass=87fy5437hdq|/

**Comment by zerotamaitsu** [comment]
could work, however do you know how to implement it in jtorchat? Don't you need to do platform specific callings? That might introduce unneeded complexity, especially since we are very focused on portability.

**Comment by userid0dev** [comment]
As far as i know it wouldn't work that portable. You would either need to control the whole network stream or make settings in each browser.

Firefox (Did this once myself. here's a tutorial from last.fm):
Adding a protocol handler (eg: lastfm://) for firefox (works in win/mac/linux)
Type in "about:config" in the location bar
right click, select New --> String

name of string should be: "network.protocol-handler.app.lastfm"
value should be the path to your player executable, eg "~/Last.fm/player"

for JTC it would be:
String: network.protocol-handler.app.torchat
value: /path/to/jtorchat.jar   --> Unix-based
value: C:\path\to\jtorchat.jar --> Win-based
not sure if direct link to jar would work!

**Comment by HostFat** [comment]
I think it will be enough that the client support them, then it will be a problem of someone else ( users ) to make settings in each browser/OS.

**Comment by jtorchat** [comment]
When i understand it right, the idea is that Clickable links can use for more then only http and https transfer.
For the Broswer i use a special variable in java. --> i can search for e-mail client and other programms.

Can you write  please all protocols for Firefox ans a prefix for mails like mail//test@web.de ?
The i will add this in the Clickable links class.

**Comment by zerotamaitsu** [comment]
Closing this issue to help keep issues tidy. (resubmit it later perhaps? This time addressing whatever 'jtorchat' commented above is needed.)
