### ISSUE TITLE
jtorchat crashing

### ISSUE THREAD

**Issue by Xexizy** [jtorchat/jtorchat-old#13]
It seems if you leave jtorchat running long enough it will crash. The window with the list of buddies is black and the chat windows freeze. I dont know what triggers this but its whenever i go afk and then come back to find its crashed.

**Comment by Porlington** [comment]
I have also noticed this, but it seems to occur more often when randomly selecting text in the log window with log trimming on (for me anyways) as I have never experienced the freeze without log trimming on.

**Comment by jtorchat** [comment]
In the Settings you can set off full log, then he delete all old log messages and block not all the memory.
When it then crash please write again and get us more Information over your system (os, java version)

**Comment by zerotamaitsu** [comment]
http://stackoverflow.com/questions/378754/java-swing-ui-crash-debugging - maybe this might help

anyway here is just an additional note: V0.7.8 is suffering from unexplained jtorchat freezes in windows, and had to be taskkilled. In addition, after taskkilled, tor.exe remained active, blocking any further jtorchat reactivation.

Are we perhaps missing a try catch statement somewhere? Maybe in the GUI?

**Comment by ghost** [comment]
Following:
One Night jtorchat freeze until 5 minutes at every start.
Today jtorchat works since more then an hour without problems.

**Comment by ghost** [comment]
Have somebody a idea, i have search Today for it but i not found anything.
Eclipse mean all is perfect.

**Comment by ghost** [comment]
I hope i have fixed it in this Version when not please create a new issue for it.
