### ISSUE TITLE
The Linster Port is in use

### ISSUE THREAD

**Issue by Xexizy** [jtorchat/jtorchat-old#15]
Hey, it seems that whenever i try to restart jtorchat i cant start it up again because it comes up with a message saying the listener port is in use. Help?

**Comment by zerotamaitsu** [comment]
if listener port is in use. look for and kill tor.exe or obfsproxy.exe in
process manager. Its a bug

On Thu, Apr 12, 2012 at 6:57 PM, Xexizy <
reply@reply.github.com

**Comment by Xexizy** [comment]
I do that but tor browser also uses tor.exe so I kind of have to guess sometimes. Also it means I cant get a batch/bash file to do it seeing as it would kill both processes. Oh, also you need to kill the javaw.exe if you needed to close jtorchat due to it crashed, which is the only time i need to close it.

**Comment by userid0dev** [comment]
in jtorchat you can use the tor instance from tor browser. just go to the settings->Advanced->Initial Tor Portable at start  and disable this option.
Then you may need to manually set the Tor socks port to the same as in tor browser.

**Comment by zerotamaitsu** [comment]
That is the recommended option, to set your own tor instance. It does
require manual configuration of system tor however, so its for advance
users only.

[ coders, perhaps we should give the user 3 different options to start
jtorchat. Normal mode of booting off portable tor (for newbies), 'System
tor' with portable torrc {this mode is usually active in non supported OS
by default} (powerusers who can set "$PATH" variables to include tor
executable. E.g. in linux), or 'manual tor' where they have to configure
everything themselves (advance users) ) ]

On Sat, Apr 14, 2012 at 8:17 AM, userid0dev <
reply@reply.github.com

**Comment by jtorchat** [comment]
Normaly we user other Ports then the config from firefox bundle and you can start more then one tor.exe with different ports.
So when jtorchat is down and you restart it he can use these ports when the old tor process from jtorchat is down.
(the problem is that this is buggy because java and the kill process function)

**Comment by Xexizy** [comment]
Might as well close this issue now seeing as a way to kill the processes has been solved on another issue, thus fixing this one.
