### ISSUE TITLE
Dont enable obfsproxy!

### ISSUE THREAD

**Issue by Xexizy** [jtorchat/jtorchat-old#17]
Hey, a while ago I discovered enabling obfsproxy in advanced settings will make it so you cant start up jtorchat again, even when you restart your computer (I know, terrifying that turning it off and on again wont work) so you would have to reinstall it.

**Comment by zerotamaitsu** [comment]
That is really quite weird. Didn't we disable obfsproxy by default
nowadays? It seems obfsproxy is still a bit too much of a prototype, and
should only be used by those desperate to break though enhanced countrywide
firewalls.

On Sat, Apr 14, 2012 at 12:37 AM, Xexizy <
reply@reply.github.com

**Comment by jtorchat** [comment]
obfproxy is only for people who can not connect over the normal way (iran) and it is really in the alpha version.
By me i can activate and diactivate i and it works perfect (linux).
I'm sure it works in the most systems too but bugs by closing this or something else is normal.

**Comment by ghost** [comment]
Please try it again, i think in the last version i have forget to pack obf...exe so he not receive a answer.
I think it is fixed in the new version.
