### ISSUE TITLE
On fixing tor.exe shutdown - after a jtorchat crash

### ISSUE THREAD

**Issue by zerotamaitsu** [jtorchat/jtorchat-old#26]
To fix the window tor shutdown, you need to put some sort of shutdown code against tor.exe in the beginning of the program. This is to deal with the possibility of crashes

code for it should be executed after the local server is started so that if jtorchat is still running it will not kill the previous jtorchats tor

**Comment by ghost** [comment]
Am 23.04.2012 04:34, schrieb zerotamaitsu:

**Comment by ghost** [comment]
Now we have a menu to kill ol jtor.exe and jobf.exe tasks.
Works under linux and windows.
