### ISSUE TITLE
Easy update

### ISSUE THREAD

**Issue by HostFat** [jtorchat/jtorchat-old#27]
Can you make more easier to update Jtorchat?
I know that it's easy, but I want it more easier.
It's better to make it noobs-friendly.

I think that a good start is cutting all ini/txt files from the config folder in the .tar.gz archive.
Jtorchat should create them only if it doesn't found oldest during the start.

So people will be able to update Jtorchat just by extracting all files in the old installation directory.
They will not lose their configuration, their know buddies, their black/white list ...

Right know there are some txt/ini files in the .tar.gz archive that overwrite the oldest if the users extract them the precedent Jtorchat directory.

**Comment by ghost** [comment]
I good idea but we have special configs like update url and this can not in the code.
But i can create a special Update file with only new files and changes.
(most only the jar)

Thanks

**Comment by zerotamaitsu** [comment]
interesting... some of the default files are needed however.

Maybe perhaps we can create a /data/defaultconfig/ config folder, which
would be autocopied to /data/config/ if no files is seen there? That might
be a suitable compromise.

On Mon, Apr 23, 2012 at 11:21 PM, HostFat <
reply@reply.github.com

**Comment by ghost** [comment]
Ok that is possible.

What like you more:
a own update file or a normal package with this?

**Comment by zerotamaitsu** [comment]
what do you mean by that? I say this is not a very high priority task, as
we are still in developing stage. This particular feature is essentially a
'ease of upgrading' feature, and is not that hard to implement after all
the more important features are done. (I personally just only copy over the
/hidden_service/ folder in /data/tor/ to a new copy of jtorchat)

Lets just focus on groupchat first, as we are wayyyy behind scheduled for
that feature. In addition groupchat will assist us as a group in
coordinating between each other about jtorchat (e.g. group meetings about a
new feature).

On Tue, Apr 24, 2012 at 1:57 PM, daux2a <
reply@reply.github.com

**Comment by HostFat** [comment]
The defaultconfig folder idea seems good.
I think that it's better to have only one package for everything.

**Comment by ghost** [comment]
Groupchat take many time, this is a little feature.
There is no problem to add them for the next Version.

**Comment by ghost** [comment]
Is added in the new Version, thanks.
