### ISSUE TITLE
jtorchat randomly crashes - at V0.7.8 - Fix ASAP!

### ISSUE THREAD

**Issue by zerotamaitsu** [jtorchat/jtorchat-old#28]
This is getting pretty annoying. Somehow jtorchat is randomly crashing, and I have no idea why its doing that.

Porlington, have you got any pointers how this can be fixed? (basically the jtorchat window freezes and blacks out)

This is pretty urgent, as its a freezing bug

**Comment by zerotamaitsu** [comment]
I think it just crashed on me just then. The latest version. restarting and testing again. (btw your 'tor.exe' kill works, so good work on that)

**Comment by zerotamaitsu** [comment]
Okay, it seems to crash still randomly. However it doesn't 'black out' now, but it shows strange GUI glitches and still freezes. I think it sounds like a GUI problem.

**Comment by zerotamaitsu** [comment]
Okay on futher observations I can better describe the symptoms:
1. normal chatting, then after some time...
2. You find that any more messages ends up with [delayed]
3. You then check buddylist, but for some reason, that person is still shown as online.
4. When you click that person's name, the program starts to freeze.

Judging from the behaviour, its might be an error with buddylist handling. Maybe its the 'holy' feature edits?

**Comment by ghost** [comment]
It is not Holy list and it was not the Trim function
 (i have revert them to the old function)
The blacklist use the same method as the holy list
and this has worked more then two versions ago.

We need totally Debug these error that means we need
a method to get this when we want (for debuging with eclipse).

It is very bad that the bug is in the actually Version but good that
kill tor.exe works now this function has need many changes in the commits.

For the next Version i try to debug the error then i should find the
problem fast.

**Comment by zerotamaitsu** [comment]
In this page: http://www.seas.gwu.edu/~simhaweb/java/faq/faq.html

Why does a Swing GUI freeze or lock up?

Solution: Most likely because the event-handling thread is being forced
into "busy" work.

need swingutilities.runlater() w/e the method was called Event Dispatch
Thread
This is since swing is not thread safe.

All the code that changes gui just needs to be surrounded with some other
code

SwingUtilities.runLater(new Runnable() {
public void run() {
gui changing code goes in here (MUST NOT TAKE LONG TIME TO EXECUTE, IE NO
CALCULATIONS OR FETCHING DATA FROM NETWORK)
}

I think.

btw the EventDispatchThread handles all the GUI updating everywhere (aka
repainting, if something takes too long on it, the gui will lockup, as all
events are parsed on it). And all swing (GUI) updating is supposed to be
done on the EDT as swing is /not/ thread safe

On Mon, Apr 30, 2012 at 6:56 PM, daux2a <
reply@reply.github.com

**Comment by ghost** [comment]
New fix by Porlington in the newest Version: 0.7.10 --> EDT
