### ISSUE TITLE
On start, check and kill any errant tor processes in both windows and linux

### ISSUE THREAD

**Issue by zerotamaitsu** [jtorchat/jtorchat-old#4]
windows and linux should have some sort of command that allows us to kill old processes by process ID (e.g. taskkill)

jtorchat sometimes may not start because an old tor process was not shutdown properly. We need to on start of tor, write down the PID. On second start, if that tor PID is still booted, then we need to kill that process, and restart it.

A potential method that can do this is 

java.lang.Runtime.exec 

I presume its a case of checking if running linux or windows, and then running the right java.lang.Runtime.exec command.

---

For windows: http://www.addictivetips.com/windows-tips/kill-processes-from-the-command-prompt-in-windows-7/

**Comment by jtorchat** [comment]
on both system the automatically kill function from java not work correct.
I have fix it under linux with pid but under windows it not work.

The problem is that we not can kill any tor, but we can try to find a pid under windows or the alternative that is the problem.

**Comment by zerotamaitsu** [comment]
hmmm... would this give you any ideas on what to do? (btw check your email)

@echo off

#CONTENT OF start_jtorchat.bat
jtorchat.exe
echo Dont press any key until you have closed jTorchat
pause
taskkill /F /IM obfsproxy.exe

**Comment by Xexizy** [comment]
Thats my batch file I made btw, and if you want it to work for this problem it would be 

@echo off

jtorchat.exe
echo Dont press any key until you have closed jTorchat
pause
taskkill /F /IM tor.exe

However be warned, this will also brake tor browser if you are using it due to the browser also using a process called tor.exe

**Comment by jtorchat** [comment]
This is bad for all people how have more then one tor.exe running.
That is always a windows problem on linux i have a pid from the task.

**Comment by zerotamaitsu** [comment]
Can't we do some sort of pid equivalence for windows? I'm sure windows
processes have an id too.

On Sat, Apr 14, 2012 at 2:14 PM, jtorchat <
reply@reply.github.com

**Comment by Xexizy** [comment]
Cant you just change the name of the process to jtor or something?

**Comment by jtorchat** [comment]
This is a solution, but not fine.
When we do this you can only run one jtorchat instance but what when you will run two seperate?

**Comment by Xexizy** [comment]
When you try to run two jtorchat instances on the second one it says "the listener port is in use" and wont start up

**Comment by Porlington** [comment]
If you are trying to run two separate instances of jtorchat it would be more efficient to run your own tor instance configured for it.

Also, adding `PidFile tor.pid` to torrc will save tors pid in tor.pid.

**Comment by zerotamaitsu** [comment]
that "PidFile tor.pid" is a good idea, at least that will tackle the first
problem of identifying the process. Now once that is done, we just need to
work out how to kill each errant process for each platform. I think it
should be done in TorLoader.java during the 'startup OS' detection stage.

On Mon, Apr 16, 2012 at 5:25 AM, Porlington <
reply@reply.github.com

**Comment by jtorchat** [comment]
on linux pidfile already work but "PidFile tor.pid" on Windows?

**Comment by zerotamaitsu** [comment]
Okay here is the plan. We will add 'shutdown tor via pid number' for windows. But it will be during shutdown of jtorchat, not during the beginning (because we don't know of the old jtorchat is still running or not).

It wasn't fixed before, because we assumed that processbuilder would close tor.exe . Well it doesn't always do that.

**Comment by zerotamaitsu** [comment]
http://stackoverflow.com/questions/4633678/how-to-kill-a-process-in-java-given-a-specific-pid

**Comment by ghost** [comment]
We have now a menu to kill old jtor.exe and jobf.exe tasks.
Works on linux and windows. (seperate commands).
